# Generated by Django 4.0.5 on 2022-06-11 15:40

from django.db import migrations

from documents.migrations.manual.webp_thumbnails import convert_thumbnails_to_webp


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1020_merge_20220518_1839"),
    ]

    operations = [
        migrations.RunPython(
            code=convert_thumbnails_to_webp,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
